# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title C Read
#'
#'@description Custom csv parser built using c++. For now it's just a test, and it is a little slower than R's read.csv, but in the future will have other custom utils
#'@param fileName name of the file or path leading to it.
#'@param header Indicates if the header is included in the file.
#'@export
cread_csv <- function(fileName, header) {
    .Call('_helpeR_cread_csv', PACKAGE = 'helpeR', fileName, header)
}

#'@title Negative Cleaner
#'@description Substitutes all the negative values in the given Data Frame for 0.
#'@param x The Data Frame user wishes to process.
#'@export
negclean <- function(x) {
    invisible(.Call('_helpeR_negclean', PACKAGE = 'helpeR', x))
}

neural_arrange <- function(df) {
    .Call('_helpeR_neural_arrange', PACKAGE = 'helpeR', df)
}

#'@title Validation
#'
#'@description Crosses georreferenced classification predictions with their respective validation tables. Both tables must have columns named X, Y, and Prediction
#'@param valid Validation data frame
#'@param predic Prediction data frame
#'@export
validation <- function(valid, predic) {
    .Call('_helpeR_validation', PACKAGE = 'helpeR', valid, predic)
}

